development:
  secret_key_base: b4de9be3a4385ca67fdb1fed3599bf7b4f95f8480c41e636f6ab860e624539980765d09bf7a95d5b1decaebc025881f06062856862c314a9c371ebd3a48b4595

test:
  secret_key_base: b4de9be3a4385ca67fdb1fed3599bf7b4f95f8480c41e636f6ab860e624539980765d09bf7a95d5b1decaebc025881f06062856862c314a9c371ebd3a48b4595

staging:
  secret_key_base: b4de9be3a4385ca67fdb1fed3599bf7b4f95f8480c41e636f6ab860e624539980765d09bf7a95d5b1decaebc025881f06062856862c314a9c371ebd3a48b4595

local_staging:
  secret_key_base: b4de9be3a4385ca67fdb1fed3599bf7b4f95f8480c41e636f6ab860e624539980765d09bf7a95d5b1decaebc025881f06062856862c314a9c371ebd3a48b45zz

aliyun_staging:
  secret_key_base: b4de9be3a4385ca67fdb1fed3599bf7b4f95f8480c41e636f6ab860e624539980765d09bf7a95d5b1decaebc025881f06062856862c314a9c371ebd3a48b45zz

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
