default: &default
#  corpid: "corpid"
#  corpsecret: "corpsecret"
#  agentid:  1
# Or if using public account, only need above two line
  appid: "wxe1e41bc95e1ffc98"
  secret: "5ed88d0faa88ba705a31e650791c5d85"
  token:  "mytoken"
  #access_token: "tmp/wechat_access_token"
  #encrypt_mode: false # if true must fill encoding_aes_key
  #encoding_aes_key:  "my_encoding_aes_key"
  #jsapi_ticket: "tmp/wechat_jsapi_ticket"
  trusted_domain_fullname: "http://getstore.cn"

production:
  corpid:     <%= ENV['WECHAT_CORPID'] %>
  corpsecret: <%= ENV['WECHAT_CORPSECRET'] %>
  agentid:    <%= ENV['WECHAT_AGENTID'] %>
# Or if using public account, only need above two line
#  appid:
#  secret:
  token:      <%= ENV['WECHAT_TOKEN'] %>
  timeout:    30,
  skip_verify_ssl: true
  access_token:  <%= ENV['WECHAT_ACCESS_TOKEN'] %>
  encrypt_mode: false # if true must fill encoding_aes_key
  encoding_aes_key:  <%= ENV['WECHAT_ENCODING_AES_KEY'] %>
  jsapi_ticket: <%= ENV['WECHAT_JSAPI_TICKET'] %>
  oauth2_cookie_duration: <%= ENV['WECHAT_OAUTH2_COOKIE_DURATION'] %> # seconds

aliyun_staging:
  appid: <%= ENV['WECHAT_APPID'] %>
  secret: <%= ENV['WECHAT_SECRET'] %>
  token:  <%= ENV['WECHAT_TOKEN'] %>

development:
  <<: *default
  trusted_domain_fullname: "http://testwx.getstore.cn"

test:
  <<: *default

# Multiple Accounts
#
# wx2_development:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#  access_token: "tmp/wechat_access_token2"
#  jsapi_ticket: "tmp/wechat_jsapi_ticket2"
#
# wx2_test:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx2_production:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx3_development:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#  access_token: "tmp/wechat_access_token3"
#  jsapi_ticket: "tmp/wechat_jsapi_ticket3"
#
# wx3_test:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx3_production:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
